### ISSUE TITLE
When run from the command line init throws an exception on names with spaces

### ISSUE THREAD

**Issue by KrisSiegel** [npm/init-package-json#16]
npm's name field does not support spaces (at some point this would be nice to update) but when running ```npm init``` in the command line then specifying a name with spaces it will continue through the entire process then fail at the end.

Suggest adding validation to the entered fields to avoid a failing at the end causing the user to re-enter all of their information again just to correct one field.

**Comment by michaelnisi** [comment]
I believe this can be closed.

**Comment by othiym23** [comment]
I believe you are correct! Thanks, @michaelnisi!
