### ISSUE TITLE
Document configuration

### ISSUE THREAD

**Issue by rstacruz** [npm/init-package-json#21]
It seems that it listens for a bunch in certain config keys (like `init.license`). It would be nice to document these somewhere.

I think they are:
- `init.license` — defaults to `ISC`
- `init.version` — defaults to `1.0.0`
- `init.author.name`
- `init.author.email`
- `init.author.url`

And you can set them via:

``` sh
$ npm config set init.author.name "Lightning McQueen"
```

**Comment by iamstarkov** [comment]
They are documented here as well https://docs.npmjs.com/misc/config#init-module
