### ISSUE TITLE
[BUG] npm init not working - throws error

### ISSUE THREAD

**Issue by javedbartlett** [npm/init-package-json#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running npm init, i receive a generic error. I've tried different folders, but it makes no difference. It seems to work fine with yarn. I've tried running different versions of Node and Npm. I've tried with or without NVM, but the same error occurs on Sonoma.

<img width="570" alt="image" src="https://github.com/npm/init-package-json/assets/48427864/6a1c8115-d282-4bb5-978b-6660089ac3d5">

### Expected Behavior

I expect no error, and to be walked through the npm init tutorial.

### Steps To Reproduce

1. open terminal and change directory to a new project folder
2. run `npm init` or `npm init -y`
3. ---> see error

### Environment

- npm: 10.2.4
- Node: 20.11.1
- OS: Mac OS Sonoma 14.2.1
- platform: Macbook Pro

**Comment by javedbartlett** [comment]
Attached is the error log file.

[2024-01-17T03_07_33_691Z-debug-0.log](https://github.com/npm/init-package-json/files/13958147/2024-01-17T03_07_33_691Z-debug-0.log)

**Comment by javedbartlett** [comment]
To add, upon creating a blank package.json file manually and attempt to run npm init. I encounter another error:

<img width="568" alt="Screenshot 2024-01-16 at 10 14 34 PM" src="https://github.com/npm/init-package-json/assets/48427864/e1f9ca35-25c0-4e7e-9503-8eebb41ec28e">

[2024-01-17T03_14_22_540Z-debug-0.log](https://github.com/npm/init-package-json/files/13958162/2024-01-17T03_14_22_540Z-debug-0.log)

**Comment by wraithgar** [comment]
I can't reproduce this.  The log seems to indicate that you are typing `npm run init` not `npm init`.  The error `missing script: init` also indicates this.

This is not an npm bug, it appears you have some sort of os alias or config that is doing this.

**Comment by javedbartlett** [comment]
@wraithgar you're correct. It seems like an old script snuck into my `.zshrc`: `alias npm='npm run '`

Thank you!
