### ISSUE TITLE
Fetch default license from LICENSE

### ISSUE THREAD

**Issue by brandonhorst** [npm/init-package-json#28]
`npm init` does a great job of intelligent defaults (name from directory name, repo url from .git, and so forth). However, even when there is a `LICENSE` file specifying a license, `npm init` pulls its default license from `config:init-license`. Pulling at least the most common few licenses from `LICENSE` would be really slick.

> Copied from https://github.com/npm/npm/issues/6947

**Comment by dkundel** [comment]
I actually came here to create an issue for this. I tend to initialize a project with the respective `LICENSE` file on GitHub and run `npm init -y` afterwards. Would be great if it would detect the license automatically. 

If this is something you would be up to have, I would be happy to look into creating a PR for this.
