### ISSUE TITLE
make default version 0.1.0

### ISSUE THREAD

**Issue by charlierudolph** [npm/init-package-json#35]
New projects are typically in very exploratory phase and may have many breaking changes early on. To stick with semantic versioning I think its better to have a default version of 0.1.0 instead of 1.0.0.

**Comment by othiym23** [comment]
Semver behavior for versions less than 1.0.0 is confusing and hard to understand and correctly depend upon. The default version was changed from 0.0.0 to 1.0.0 for exactly this reason. See this thread for context: https://github.com/npm/node-semver/issues/79. The current behavior seems to be working better than not. People can still choose to set a version less than 1.0.0 at init time if they choose, and the default gently nudges people towards the world of cheap integers / actually incrementing the major version when it makes sense.
