### ISSUE TITLE
Invalid names result in crash in error handler

### ISSUE THREAD

**Issue by iarna** [npm/init-package-json#37]
```
$ npm init
```
…
```
name: (bar) fooBar
```
…
```
npm ERR! Cannot read property 'join' of undefined
```

And the stack trace ultimately points here:

[init-package-json/default-input.js:51:44](https://github.com/npm/init-package-json/blob/master/default-input.js#L51)

**Comment by michaelnisi** [comment]
https://github.com/npm/init-package-json/pull/39

**Comment by michaelnisi** [comment]
Done.
