### ISSUE TITLE
new init variable github init.github.username

### ISSUE THREAD

**Issue by iamstarkov** [npm/init-package-json#50]
Right now, `npm init` is working well for me and the only routine is to type `iamstarkov/new-repo` into repo field suggestion.

So I want to request new init variable `init.github.username` and to suggest github repo’s name from folder name. What do you think?

If this idea is welcome I can try to implement it and send a patch

**Comment by tunnckoCore** [comment]
:+1: for the idea

for username default we can use that is in `~/.gitconfig` or from local .git folder config

some links
https://github.com/jonschlinkert/git-username
https://github.com/jonschlinkert/git-user-name
https://github.com/jonschlinkert/git-user-email

**Comment by iamstarkov** [comment]
@othiym23 @isaacs what do you think?

**Comment by iamstarkov** [comment]
I end up with my own generator https://github.com/iamstarkov/generator-tiny-es-nm /cc @tunnckoCore
