### ISSUE TITLE
[QUESTION] Is this module duplicating my `optionalDependencies` to `dependencies`?

### ISSUE THREAD

**Issue by christianbundy** [npm/init-package-json#93]
# What / Why

I'm trying to debug https://github.com/npm/cli/issues/724 and I think maybe this module is responsible? It seems like maybe [`readDeps()`](https://github.com/npm/init-package-json/blob/2b5d21ea3e3434f8e0d6050cd2733d5062b830c6/default-input.js#L18-L46) could be the culprit, but I'm not sure.

## Where

* n/a

## Who

* n/a

## References

* Related to https://github.com/npm/cli/issues/724

**Comment by ruyadorno** [comment]
should have been fixed by https://github.com/npm/init-package-json/commit/da71c0503e67d6fda4fa4ff0ccea052494e48917 👍  thanks for reporting it @christianbundy !
