### ISSUE TITLE
Wrong message in link for "help"

### ISSUE THREAD

**Issue by jrschmidt** [npm/init-package-json#94]
When you type `npm init`, it says "See `npm help json` for definitive documentation on these fields
and exactly what they do." When you type this says `No results for "json"`.

If you type `npm help init` you receive the correct help page.

The message should be changed to say "See `npm help init` ..."

**Comment by killshot13** [comment]
I just attempted to reproduce and was unsuccessful. This issue appears to be fixed, at least in the LTS version. (npm v6.14.10) Requesting update to close the issue. Thank you!
![npm-init-pkg-json#94](https://user-images.githubusercontent.com/47695475/103930279-1cbf5980-50e4-11eb-81a3-30a56ebeec81.jpg)
